### ISSUE TITLE
App.import is not a function. Including ember-cli-swiper in an addon dependecy

### ISSUE THREAD

**Issue by ledes** [Suven/ember-cli-swiper#19]
After creating an addon and including ember-cli-swiper as one of the dependencies I'm getting the following error when I run "ember server" or "ember test"

`app.import is not a function
TypeError: app.import is not a function`

Similar issue and possible solution
https://github.com/ember-cli/ember-cli/issues/3718
https://github.com/tomdale/ember-network/pull/7/files

**Comment by DegreeDev** [comment]
I agree this is an issue. 

I've been able to get around the issue locally with the suggestion in [ember-cli/ember-cli#3718](https://github.com/ember-cli/ember-cli/issues/3718) which is essentially updating the index.js to call: 

`this._super.included.apply(this, arguments);`

instead of 

`this._super.included(app);`

I'm running a slightly different configuration because we are using engines (which are technically addons) but I still think this applies.

**Comment by Suven** [comment]
The suggestion DegreeDev made, is already reflected in a commit some days ago. I will create a new release with that in a few hours.

**Comment by Suven** [comment]
fixed in e210f272a1b7d85f75c470a4651b9c45d7fdafb4 and released in d352674e6403ad578a8e00729cafd318bbad48df (0.6.0)
